### ISSUE TITLE
Hi, thanks for the effort but I could not make it work.

### ISSUE THREAD

**Issue by engblnk** [yko/mojolicious-example-ajax#1]
C:\Users\eng\Documents\GitHub\mojolicious-example-ajax> script/ajax-example daemon
'script' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yko** [comment]
Hi @ebulanik 
thanks for your interest.
Mojolicious framework changed a lot since I've touched this repo, which is about  four years.
So I've fixed that just for fun.
You have to specify an interpreter to run it on Windows anyway, just a script is not executable by default, so you better try something like 

```
perl <script> [arguments]
```

**Comment by engblnk** [comment]
great, thanks.
